steps:
  # Set up QEMU for multi-architecture support
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

  # Set up Docker Buildx
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap

  # Build and push for multiple architectures with caching
  - name: "gcr.io/cloud-builders/docker"
    id: Build and Push
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/guisurfer/surfpizza:latest \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/guisurfer/surfpizza:${SHORT_SHA}  \
          --cache-from type=registry,ref=us-central1-docker.pkg.dev/$PROJECT_ID/guisurfer/surfpizza:buildcache \
          --cache-to type=registry,ref=us-central1-docker.pkg.dev/$PROJECT_ID/guisurfer/surfpizza:buildcache,mode=max \
          --push \
          .

  # Verify the multi-arch image
  - name: "gcr.io/cloud-builders/docker"
    id: Verify Images
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker buildx imagetools inspect us-central1-docker.pkg.dev/$PROJECT_ID/guisurfer/surfpizza:latest
        docker buildx imagetools inspect us-central1-docker.pkg.dev/$PROJECT_ID/guisurfer/surfpizza:${SHORT_SHA}

timeout: "3600s"

options:
  machineType: "N1_HIGHCPU_8"
